# -*- coding: utf-8 -*-
"""sanskrit_nmt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JfTGTKqrhWaypfeps6YFlcNP3SS3-DpA

!pip install -q
"""

import nltk
nltk.download('punkt')

import re
import time
import random
import math
from collections import Counter

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import matplotlib.pyplot as plt



SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', DEVICE)

from google.colab import drive
drive.mount('/content/drive')

# EDIT this path to wherever your 6 CSVs live
DATA_DIR = '/content/drive/MyDrive/sanskrit-nmt/data/'

def load_split(split):
    suffix = '_10000' if split == 'train' else '_1000'
    sa = pd.read_csv(f'{DATA_DIR}{split}_sa{suffix}.csv')
    en = pd.read_csv(f'{DATA_DIR}{split}_en{suffix}.csv')
    df = pd.merge(sa, en, on='Source_id')
    return df

train_df = load_split('train')
dev_df   = load_split('dev')
test_df  = load_split('test')

print('train:', train_df.shape, ' dev:', dev_df.shape, ' test:', test_df.shape)
train_df.head()

"""## Preprocessing & Vocabulary"""

PAD_IDX, SOS_IDX, EOS_IDX, UNK_IDX = 0, 1, 2, 3
SPECIAL_TOKENS = ['<pad>', '<sos>', '<eos>', '<unk>']


def tokenize(text):
    text = str(text).strip()
    # separate common punctuation (including Devanagari danda '।') from words
    text = re.sub(r'([।,.!?;:"\'()])', r' \1 ', text)
    return text.split()

class Vocab:
    def __init__(self, sentences, min_freq=1):
        counter = Counter()
        for s in sentences:
            counter.update(tokenize(s))
        self.itos = list(SPECIAL_TOKENS)
        for word, freq in counter.items():
            if freq >= min_freq:
                self.itos.append(word)
        self.stoi = {w: i for i, w in enumerate(self.itos)}

    def encode(self, text, max_len=None):
        ids = [self.stoi.get(t, UNK_IDX) for t in tokenize(text)]
        ids = [SOS_IDX] + ids + [EOS_IDX]
        if max_len:
            ids = ids[:max_len]
        return ids

    def decode(self, ids):
        words = []
        for i in ids:
            if i == EOS_IDX:
                break
            if i in (PAD_IDX, SOS_IDX):
                continue
            words.append(self.itos[i])
        return ' '.join(words)

    def __len__(self):
        return len(self.itos)

SRC_VOCAB = Vocab(train_df['Sentence_sa'].tolist(), min_freq=1)
TGT_VOCAB = Vocab(train_df['Sentence_en'].tolist(), min_freq=1)
print('Sanskrit vocab size:', len(SRC_VOCAB))
print('English vocab size :', len(TGT_VOCAB))

"""## Dataset & DataLoader"""

MAX_LEN = 64

class TranslationDataset(Dataset):
    def __init__(self, df, src_vocab, tgt_vocab, max_len=MAX_LEN):
        self.df = df.reset_index(drop=True)
        self.src_vocab = src_vocab
        self.tgt_vocab = tgt_vocab
        self.max_len = max_len

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        src_ids = self.src_vocab.encode(row['Sentence_sa'], self.max_len)
        tgt_ids = self.tgt_vocab.encode(row['Sentence_en'], self.max_len)
        return torch.tensor(src_ids), torch.tensor(tgt_ids)

def collate_fn(batch):
    srcs, tgts = zip(*batch)
    src_lens = torch.tensor([len(s) for s in srcs])
    src_pad = nn.utils.rnn.pad_sequence(srcs, batch_first=True, padding_value=PAD_IDX)
    tgt_pad = nn.utils.rnn.pad_sequence(tgts, batch_first=True, padding_value=PAD_IDX)
    return src_pad, src_lens, tgt_pad

BATCH_SIZE = 32

train_ds = TranslationDataset(train_df, SRC_VOCAB, TGT_VOCAB)
dev_ds   = TranslationDataset(dev_df, SRC_VOCAB, TGT_VOCAB)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, collate_fn=collate_fn)
dev_loader   = DataLoader(dev_ds, batch_size=BATCH_SIZE, shuffle=False, collate_fn=collate_fn)

print('train batches:', len(train_loader), ' dev batches:', len(dev_loader))

"""## Model — Encoder
Bidirectional GRU encoder. Packs padded sequences for efficiency.
"""

class Encoder(nn.Module):
    def __init__(self, vocab_size, emb_dim, hid_dim, n_layers=1, dropout=0.3):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, emb_dim, padding_idx=PAD_IDX)
        self.rnn = nn.GRU(emb_dim, hid_dim, n_layers, bidirectional=True,
                           batch_first=True, dropout=dropout if n_layers > 1 else 0)
        self.fc = nn.Linear(hid_dim * 2, hid_dim)
        self.dropout = nn.Dropout(dropout)

    def forward(self, src, src_lens):
        embedded = self.dropout(self.embedding(src))
        packed = nn.utils.rnn.pack_padded_sequence(
            embedded, src_lens.cpu(), batch_first=True, enforce_sorted=False)
        packed_out, hidden = self.rnn(packed)
        outputs, _ = nn.utils.rnn.pad_packed_sequence(packed_out, batch_first=True)
        hidden = torch.tanh(self.fc(torch.cat((hidden[-2], hidden[-1]), dim=1)))
        return outputs, hidden  # outputs: (B, src_len, hid*2), hidden: (B, hid)

""" ## Model — Bahdanau (Additive) Attention"""

class Attention(nn.Module):
    def __init__(self, hid_dim):
        super().__init__()
        self.attn = nn.Linear(hid_dim * 3, hid_dim)
        self.v = nn.Linear(hid_dim, 1, bias=False)

    def forward(self, hidden, encoder_outputs, mask):
        src_len = encoder_outputs.shape[1]
        hidden_rep = hidden.unsqueeze(1).repeat(1, src_len, 1)
        energy = torch.tanh(self.attn(torch.cat((hidden_rep, encoder_outputs), dim=2)))
        attention = self.v(energy).squeeze(2)
        attention = attention.masked_fill(mask == 0, -1e10)
        return torch.softmax(attention, dim=1)  # (B, src_len)

"""## Model — Decoder (with attention)"""

class Decoder(nn.Module):
    def __init__(self, vocab_size, emb_dim, hid_dim, attention, n_layers=1, dropout=0.3):
        super().__init__()
        self.attention = attention
        self.embedding = nn.Embedding(vocab_size, emb_dim, padding_idx=PAD_IDX)
        self.rnn = nn.GRU(hid_dim * 2 + emb_dim, hid_dim, n_layers,
                           batch_first=True, dropout=dropout if n_layers > 1 else 0)
        self.fc_out = nn.Linear(hid_dim * 3 + emb_dim, vocab_size)
        self.dropout = nn.Dropout(dropout)

    def forward(self, input_tok, hidden, encoder_outputs, mask):
        input_tok = input_tok.unsqueeze(1)                     # (B,1)
        embedded = self.dropout(self.embedding(input_tok))     # (B,1,emb)
        a = self.attention(hidden, encoder_outputs, mask).unsqueeze(1)  # (B,1,src_len)
        weighted = torch.bmm(a, encoder_outputs)                # (B,1,hid*2)
        rnn_input = torch.cat((embedded, weighted), dim=2)
        output, hidden_new = self.rnn(rnn_input, hidden.unsqueeze(0))
        output, weighted, embedded = output.squeeze(1), weighted.squeeze(1), embedded.squeeze(1)
        prediction = self.fc_out(torch.cat((output, weighted, embedded), dim=1))
        return prediction, hidden_new.squeeze(0)

"""## Seq2Seq Wrapper (teacher forcing)"""

class Seq2Seq(nn.Module):
    def __init__(self, encoder, decoder, device):
        super().__init__()
        self.encoder = encoder
        self.decoder = decoder
        self.device = device

    def create_mask(self, src):
        return (src != PAD_IDX)

    def forward(self, src, src_lens, tgt, teacher_forcing_ratio=0.5):
        batch_size, tgt_len = tgt.shape
        vocab_size = self.decoder.fc_out.out_features
        outputs = torch.zeros(batch_size, tgt_len, vocab_size).to(self.device)

        encoder_outputs, hidden = self.encoder(src, src_lens)
        mask = self.create_mask(src)
        input_tok = tgt[:, 0]  # <sos>

        for t in range(1, tgt_len):
            output, hidden = self.decoder(input_tok, hidden, encoder_outputs, mask)
            outputs[:, t] = output
            top1 = output.argmax(1)
            teacher_force = random.random() < teacher_forcing_ratio
            input_tok = tgt[:, t] if teacher_force else top1
        return outputs

"""## Instantiate Model & Optimizer"""

EMB_DIM = 256
HID_DIM = 512
N_LAYERS = 1
DROPOUT = 0.3
LEARNING_RATE = 1e-3
CLIP = 1.0

attn = Attention(HID_DIM)
enc = Encoder(len(SRC_VOCAB), EMB_DIM, HID_DIM, N_LAYERS, DROPOUT)
dec = Decoder(len(TGT_VOCAB), EMB_DIM, HID_DIM, attn, N_LAYERS, DROPOUT)
model = Seq2Seq(enc, dec, DEVICE).to(DEVICE)

optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)
scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=2)
criterion = nn.CrossEntropyLoss(ignore_index=PAD_IDX)

n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f'Trainable parameters: {n_params:,}')

"""## Training & Evaluation Functions"""

def train_epoch(model, loader, optimizer, criterion, clip, tf_ratio):
    model.train()
    epoch_loss = 0
    for src, src_lens, tgt in loader:
        src, tgt = src.to(DEVICE), tgt.to(DEVICE)
        optimizer.zero_grad()
        output = model(src, src_lens, tgt, tf_ratio)
        output_dim = output.shape[-1]
        loss = criterion(output[:, 1:].reshape(-1, output_dim), tgt[:, 1:].reshape(-1))
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), clip)
        optimizer.step()
        epoch_loss += loss.item()
    return epoch_loss / len(loader)

def evaluate_epoch(model, loader, criterion):
    model.eval()
    epoch_loss = 0
    with torch.no_grad():
        for src, src_lens, tgt in loader:
            src, tgt = src.to(DEVICE), tgt.to(DEVICE)
            output = model(src, src_lens, tgt, teacher_forcing_ratio=0.0)
            output_dim = output.shape[-1]
            loss = criterion(output[:, 1:].reshape(-1, output_dim), tgt[:, 1:].reshape(-1))
            epoch_loss += loss.item()
    return epoch_loss / len(loader)

"""## Run Training"""

N_EPOCHS = 15
best_val_loss = float('inf')
train_losses, val_losses = [], []

for epoch in range(1, N_EPOCHS + 1):
    tf_ratio = max(0.3, 0.9 - 0.05 * epoch)  # decaying teacher forcing
    start = time.time()

    train_loss = train_epoch(model, train_loader, optimizer, criterion, CLIP, tf_ratio)
    val_loss = evaluate_epoch(model, dev_loader, criterion)
    scheduler.step(val_loss)

    train_losses.append(train_loss)
    val_losses.append(val_loss)

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.state_dict(), 'best_model.pt')

    mins = (time.time() - start) / 60
    print(f'Epoch {epoch:02d} | Train Loss: {train_loss:.3f} | Val Loss: {val_loss:.3f} '
          f'| PPL: {math.exp(val_loss):7.2f} | Time: {mins:.1f}m')

model.load_state_dict(torch.load('best_model.pt'))
print('Loaded best checkpoint (lowest val loss).')

"""## Training Curves (for report)"""

plt.figure(figsize=(7,4))
plt.plot(train_losses, label='Train Loss')
plt.plot(val_losses, label='Val Loss')
plt.xlabel('Epoch'); plt.ylabel('Loss'); plt.title('Training vs Validation Loss')
plt.legend(); plt.grid(alpha=0.3)
plt.savefig('loss_curve.png', dpi=150, bbox_inches='tight')
plt.show()

"""## Beam Search Decoding
Used for generating final translations
"""

def beam_search_decode(model, sentence, src_vocab, tgt_vocab, beam_width=3, max_len=MAX_LEN):
    model.eval()
    src_ids = torch.tensor(src_vocab.encode(sentence, max_len)).unsqueeze(0).to(DEVICE)
    src_len = torch.tensor([src_ids.shape[1]])

    with torch.no_grad():
        encoder_outputs, hidden = model.encoder(src_ids, src_len)
        mask = model.create_mask(src_ids)

        beams = [(0.0, [SOS_IDX], hidden)]
        completed = []

        for _ in range(max_len):
            new_beams = []
            for score, seq, hid in beams:
                if seq[-1] == EOS_IDX:
                    completed.append((score, seq))
                    continue
                input_tok = torch.tensor([seq[-1]]).to(DEVICE)
                output, hid_new = model.decoder(input_tok, hid, encoder_outputs, mask)
                log_probs = torch.log_softmax(output, dim=1).squeeze(0)
                topk_probs, topk_ids = log_probs.topk(beam_width)
                for i in range(beam_width):
                    new_beams.append((score + topk_probs[i].item(),
                                       seq + [topk_ids[i].item()], hid_new))
            if not new_beams:
                break
            new_beams.sort(key=lambda x: x[0] / len(x[1]), reverse=True)
            beams = new_beams[:beam_width]

        completed.extend([(s, sq) for s, sq, _ in beams])
        completed.sort(key=lambda x: x[0] / len(x[1]), reverse=True)
        return tgt_vocab.decode(completed[0][1])

# quick sanity check on a dev example
sample = dev_df.iloc[0]
print('Source :', sample['Sentence_sa'])
print('Reference:', sample['Sentence_en'])
print('Prediction:', beam_search_decode(model, sample['Sentence_sa'], SRC_VOCAB, TGT_VOCAB))

"""## Generate Predictions for Test Set"""

predictions = []
start_time = time.time()

for _, row in test_df.iterrows():
    pred = beam_search_decode(model, row['Sentence_sa'], SRC_VOCAB, TGT_VOCAB, beam_width=3)
    predictions.append(pred)

inference_time = time.time() - start_time
print(f'Inference time for {len(test_df)} sentences: {inference_time:.2f}s')

submission = pd.DataFrame({
    'Source_id': test_df['Source_id'],
    'Sentence_en': predictions
})
submission.to_csv('submission.csv', index=False, encoding='utf-8')
submission.head()

""" ## Evaluation — BLEU

"""

from nltk.translate.bleu_score import corpus_bleu

references = [[tokenize(ref)] for ref in test_df['Sentence_en'].tolist()]
hypotheses = [tokenize(pred) for pred in predictions]

bleu_score = corpus_bleu(references, hypotheses)
print(f'BLEU score: {bleu_score:.4f}')

!pip install -q bert-score

"""## Evaluation — BERTScore (F1, rescaled with baseline)"""

from bert_score import score as bert_score_fn

P, R, F1 = bert_score_fn(
    predictions,
    test_df['Sentence_en'].tolist(),
    lang='en',
    rescale_with_baseline=True
)
print(f'BERTScore F1 (mean): {F1.mean().item():.4f}')

"""## Evaluation — Efficiency (Time & Parameters)"""

n_params = sum(p.numel() for p in model.parameters())
print(f'Total parameters: {n_params:,}')
print(f'Total inference time on test set: {inference_time:.2f} seconds')
print(f'Avg time per sentence: {inference_time/len(test_df)*1000:.2f} ms')

"""## Translation Examples & Error Analysis (for report)"""

n_examples = 8
sample_idx = np.random.choice(len(test_df), size=n_examples, replace=False)

for i in sample_idx:
    src = test_df.iloc[i]['Sentence_sa']
    ref = test_df.iloc[i]['Sentence_en']
    pred = predictions[i]
    print(f'Source    : {src}')
    print(f'Reference : {ref}')
    print(f'Prediction: {pred}')
    print('-' * 60)

submission.to_csv('/content/drive/MyDrive/submission.csv', index=False)
print("Saved!")

